[[dependency]]
org = "ballerina"
name = "time"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "task"
version = "1.2.0-alpha5"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"
